name: ok_edus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  connectivity_plus: ^4.0.2
  circular_bottom_navigation: ^2.3.0
  dio: ^5.0.0
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.3.0
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.2
  file_picker: ^5.3.4
  http: ^1.1.0
  url_launcher: ^6.0.9
  youtube_player_flutter: ^8.1.2
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.4.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.3

flutter_native_splash:
  andriod: true
  ios: true
  web: false

  #color: "#FFCC00"
  background_image: "images/Splash.png"
  image: "images/logo_edus2.png"

  android_12:
   image: "images/logo4.png"
   
  
   
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - translations/

